### ISSUE TITLE
UI screens for Assets

### ISSUE THREAD

**Issue by luizstacio** [FuelLabs/fuels-wallet#60]
## Subtasks

- [x] List of assets
- [x] Add Asset - Search
- [x] Add Asset - Custom Asset
