### ISSUE TITLE
Create README for the project

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/fuels-wallet#83]
## Tasks

- [ ] Stack used
- [ ] How run the project
- [ ] About systems architecture
- [ ] About XState typegen
